version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: farmermarket
      POSTGRES_USER: farmermarket
      POSTGRES_PASSWORD: farmermarket
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U farmermarket"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - DATABASE_URL=postgres://farmermarket:farmermarket@db:5432/farmermarket
      - REDIS_URL=redis://redis:6379/0
      - DJANGO_SETTINGS_MODULE=markt_farme.settings
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  celery:
    build: .
    command: celery -A markt_farme worker -l info
    volumes:
      - .:/app
    environment:
      - DEBUG=True
      - DATABASE_URL=postgres://farmermarket:farmermarket@db:5432/farmermarket
      - REDIS_URL=redis://redis:6379/0
      - DJANGO_SETTINGS_MODULE=markt_farme.settings
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  celery-beat:
    build: .
    command: celery -A markt_farme beat -l info
    volumes:
      - .:/app
    environment:
      - DEBUG=True
      - DATABASE_URL=postgres://farmermarket:farmermarket@db:5432/farmermarket
      - REDIS_URL=redis://redis:6379/0
      - DJANGO_SETTINGS_MODULE=markt_farme.settings
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - web

volumes:
  postgres_data:
  redis_data:
  static_volume:
  media_volume: 