# Generated by Django 5.1.3 on 2025-04-22 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerprofile',
            name='accepted_payment_methods',
            field=models.CharField(blank=True, help_text='Méthodes de paiement acceptées séparées par des virgules', max_length=255, verbose_name='Méthodes de paiement acceptées'),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='bank_account_name',
            field=models.CharField(blank=True, help_text='Nom du titulaire du compte bancaire', max_length=255, verbose_name='Titulaire du compte'),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='bank_account_number',
            field=models.CharField(blank=True, help_text='Numéro de compte IBAN', max_length=34, verbose_name='IBAN'),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='bank_name',
            field=models.CharField(blank=True, help_text='Nom de la banque', max_length=255, verbose_name='Banque'),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='bank_swift_bic',
            field=models.CharField(blank=True, help_text='Code BIC/SWIFT de la banque', max_length=11, verbose_name='BIC/SWIFT'),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='mobile_payment_app',
            field=models.CharField(blank=True, help_text='Application de paiement mobile utilisée (ex: Paylib, Lydia)', max_length=100, verbose_name='Application de paiement'),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='mobile_payment_phone',
            field=models.CharField(blank=True, help_text='Numéro de téléphone pour les paiements mobiles', max_length=15, verbose_name='Téléphone pour paiement mobile'),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='payment_instructions',
            field=models.TextField(blank=True, help_text='Instructions spécifiques pour le paiement', verbose_name='Instructions de paiement'),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='requires_payment_confirmation',
            field=models.BooleanField(default=True, help_text='Le fermier souhaite-t-il recevoir une confirmation pour chaque paiement?', verbose_name='Confirmation de paiement requise'),
        ),
        migrations.AddField(
            model_name='order',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='farmer',
            field=models.ForeignKey(blank=True, help_text='Fermier associé à cette commande', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_confirmation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_confirmed_by_farmer',
            field=models.BooleanField(default=False, help_text='Le fermier a confirmé avoir reçu le paiement'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_instructions',
            field=models.TextField(blank=True, help_text='Instructions fournies au client pour effectuer le paiement', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_notes',
            field=models.TextField(blank=True, help_text='Notes additionnelles concernant le paiement', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_proof',
            field=models.ImageField(blank=True, help_text="Preuve de paiement (photo ou capture d'écran)", null=True, upload_to='payment_proofs/'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_reference',
            field=models.CharField(blank=True, help_text='Référence de paiement fournie par le client', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('bank_transfer', 'Virement bancaire'), ('cash', 'Paiement en espèces'), ('check', 'Chèque'), ('mobile_payment', 'Paiement mobile')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Non payée'), ('pending', 'En attente de paiement'), ('payment_proof_sent', 'Preuve de paiement envoyée'), ('payment_confirmed', 'Paiement confirmé'), ('paid', 'Payée'), ('refunded', 'Remboursée'), ('failed', 'Échec de paiement')], default='unpaid', max_length=20),
        ),
    ]
