# Generated by Django 5.1.3 on 2024-11-15 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sales_count',
            field=models.IntegerField(default=0),
        ),
    ]
