# Generated by Django 5.1.3 on 2025-04-22 22:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_farmerprofile_accepted_payment_methods_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmerprofile',
            old_name='farm_images',
            new_name='farm_image',
        ),
        migrations.RemoveField(
            model_name='farmerprofile',
            name='accepted_payment_methods',
        ),
        migrations.RemoveField(
            model_name='farmerprofile',
            name='bank_account_name',
        ),
        migrations.RemoveField(
            model_name='farmerprofile',
            name='bank_account_number',
        ),
        migrations.RemoveField(
            model_name='farmerprofile',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='farmerprofile',
            name='bank_swift_bic',
        ),
        migrations.RemoveField(
            model_name='farmerprofile',
            name='mobile_payment_app',
        ),
        migrations.RemoveField(
            model_name='farmerprofile',
            name='mobile_payment_phone',
        ),
        migrations.RemoveField(
            model_name='farmerprofile',
            name='payment_instructions',
        ),
        migrations.RemoveField(
            model_name='farmerprofile',
            name='requires_payment_confirmation',
        ),
        migrations.RemoveField(
            model_name='order',
            name='contact_phone',
        ),
        migrations.RemoveField(
            model_name='order',
            name='farmer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_confirmation_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_confirmed_by_farmer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_instructions',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_notes',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_proof',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_reference',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_address',
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='country',
            field=models.CharField(blank=True, default='Belgique', help_text='Pays', max_length=100, verbose_name='Pays'),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='specialties',
            field=models.CharField(blank=True, help_text='Produits phares ou spécialités, séparés par des virgules', max_length=500, verbose_name='Spécialités / Produits phares'),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='street',
            field=models.CharField(blank=True, help_text='Rue et numéro', max_length=255, verbose_name='Rue'),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='zip_code',
            field=models.CharField(blank=True, help_text='Code postal', max_length=10, verbose_name='Code postal'),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='address',
            field=models.CharField(blank=True, help_text='Adresse complète du fermier (champ obsolète, utiliser street à la place)', max_length=255, verbose_name='Adresse (obsolète)'),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='farmer',
            field=models.OneToOneField(limit_choices_to={'is_farmer': True}, on_delete=django.db.models.deletion.CASCADE, related_name='farmerprofile', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='postal_code',
            field=models.CharField(blank=True, help_text='Code postal du fermier (champ obsolète, utiliser zip_code à la place)', max_length=10, verbose_name='Code postal (obsolète)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('card', 'Carte de crédit'), ('cash', 'Espèces'), ('transfer', 'Virement bancaire')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Non payée'), ('processing', 'En cours de paiement'), ('paid', 'Payée'), ('refunded', 'Remboursée')], default='unpaid', max_length=20),
        ),
    ]
