# Generated by Django 5.1.3 on 2024-11-19 05:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_category_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(blank=True, help_text='Latitude for the map location', null=True)),
                ('longitude', models.FloatField(blank=True, help_text='Longitude for the map location', null=True)),
                ('description', models.TextField(blank=True, help_text='Short description about the farmer')),
                ('address', models.CharField(blank=True, help_text="Farmer's address", max_length=255)),
                ('phone_number', models.CharField(blank=True, help_text='Phone number of the farmer', max_length=15)),
                ('website', models.URLField(blank=True, help_text="Farmer's website URL")),
                ('farmer', models.OneToOneField(limit_choices_to={'is_farmer': True}, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
