# Generated by Django 5.1.3 on 2025-04-22 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_farm_images_farmerprofile_farm_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmerprofile',
            name='additional_info',
        ),
        migrations.RemoveField(
            model_name='farmerprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='farmerprofile',
            name='google_maps_link',
        ),
        migrations.RemoveField(
            model_name='farmerprofile',
            name='image_1',
        ),
        migrations.RemoveField(
            model_name='farmerprofile',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='farmerprofile',
            name='image_3',
        ),
        migrations.RemoveField(
            model_name='farmerprofile',
            name='postal_code',
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='additional_images_json',
            field=models.TextField(blank=True, help_text='Stockage JSON pour les images supplémentaires', null=True, verbose_name='Images supplémentaires (JSON)'),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='can_deliver',
            field=models.BooleanField(default=False, help_text='Le fermier propose-t-il des livraisons?', verbose_name='Propose des livraisons'),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='delivery_area',
            field=models.TextField(blank=True, help_text='Zone de livraison (codes postaux, villes, etc.)', verbose_name='Zone de livraison'),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='delivery_conditions',
            field=models.TextField(blank=True, help_text='Conditions de livraison (minimum de commande, délais, etc.)', verbose_name='Conditions de livraison'),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='email',
            field=models.EmailField(blank=True, help_text='Email de contact pour la ferme', max_length=254, null=True, verbose_name='Email de contact'),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour'),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='location_instructions',
            field=models.TextField(blank=True, help_text='Instructions pour trouver la ferme plus facilement', verbose_name='Comment trouver la ferme'),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='production_methods',
            field=models.TextField(blank=True, help_text='Description des méthodes de production', verbose_name='Méthodes de production'),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='seasonal_products',
            field=models.TextField(blank=True, help_text='Produits disponibles selon les saisons', verbose_name='Produits saisonniers'),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='country',
            field=models.CharField(blank=True, default='Belgique', help_text='Pays du fermier', max_length=100, verbose_name='Pays'),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='farm_image',
            field=models.ImageField(blank=True, help_text='Image principale représentant la ferme', null=True, upload_to='farm_images/', verbose_name='Image principale'),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='specialties',
            field=models.TextField(blank=True, help_text='Spécialités et produits phares de la ferme', verbose_name='Spécialités'),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='zip_code',
            field=models.CharField(blank=True, help_text='Code postal du fermier', max_length=10, verbose_name='Code postal'),
        ),
    ]
