# Generated by Django 5.1.3 on 2024-11-19 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_farmerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerprofile',
            name='farm_images',
            field=models.ImageField(blank=True, help_text='Téléchargez une image représentant la ferme', null=True, upload_to='farm_images/'),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='opening_hours',
            field=models.TextField(blank=True, help_text="Horaires d'ouverture de la ferme"),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='services',
            field=models.TextField(blank=True, help_text='Services supplémentaires fournis par la ferme (ex : visites, produits locaux, etc.)'),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='address',
            field=models.CharField(blank=True, help_text='Adresse complète du fermier', max_length=255),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='description',
            field=models.TextField(blank=True, help_text='Brève description du fermier et de sa ferme'),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Latitude pour la localisation sur la carte', null=True),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Longitude pour la localisation sur la carte', null=True),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Numéro de téléphone du fermier', max_length=15),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='website',
            field=models.URLField(blank=True, help_text='URL du site web du fermier'),
        ),
    ]
