# Generated by Django 5.1.3 on 2024-11-20 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_farmerprofile_farm_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
