# Generated by Django 5.1.3 on 2024-11-20 05:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_product_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerprofile',
            name='additional_info',
            field=models.TextField(blank=True, help_text='Informations supplémentaires sur la ferme (ex: histoire, méthode de culture, etc.)'),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='agriculture_sector',
            field=models.CharField(blank=True, help_text='Secteur ou branche agricole de la ferme (ex: culture, élevage, etc.)', max_length=255),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='google_maps_link',
            field=models.CharField(blank=True, help_text='Lien vers Google Maps pour localisation', max_length=255),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='services',
            field=models.TextField(blank=True, help_text='Services supplémentaires fournis par la ferme (ex: visites, produits locaux, etc.)'),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='website',
            field=models.URLField(blank=True, help_text='Site web de la ferme', null=True),
        ),
    ]
