# Generated by Django 5.1.3 on 2024-11-22 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_farmerprofile_additional_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerprofile',
            name='additional_info',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='agriculture_sector',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='farm_images',
            field=models.ImageField(blank=True, null=True, upload_to='farm_images/'),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='google_maps_link',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='opening_hours',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='services',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
