# Generated by Django 5.1.3 on 2024-11-22 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_farmerprofile_additional_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerprofile',
            name='farm_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
