# Generated by Django 5.1.3 on 2024-11-23 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_farmerprofile_farm_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmerprofile',
            name='opening_hours',
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='opening_hours_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='opening_hours_start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
