# Generated by Django 5.1.3 on 2024-11-24 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_remove_farmerprofile_opening_hours_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmerprofile',
            name='opening_hours_end',
        ),
        migrations.RemoveField(
            model_name='farmerprofile',
            name='opening_hours_start',
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='opening_hours_json',
            field=models.JSONField(default=dict),
        ),
        migrations.CreateModel(
            name='OpeningHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('lundi', 'Lundi'), ('mardi', 'Mardi'), ('mercredi', 'Mercredi'), ('jeudi', 'Jeudi'), ('vendredi', 'Vendredi'), ('samedi', 'Samedi'), ('dimanche', 'Dimanche')], max_length=10)),
                ('opening_time', models.TimeField(blank=True, null=True)),
                ('closing_time', models.TimeField(blank=True, null=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('farmer_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hours_of_operation', to='products.farmerprofile')),
            ],
        ),
    ]
