# Generated by Django 5.1.3 on 2024-11-24 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_remove_farmerprofile_opening_hours_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerprofile',
            name='farm_name',
            field=models.CharField(max_length=255),
        ),
    ]
