# Generated by Django 5.1.3 on 2024-11-24 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_farmerprofile_farm_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmerprofile',
            name='google_maps_link',
        ),
    ]
