# Generated by Django 5.1.3 on 2025-04-02 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_remove_farmerprofile_google_maps_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='openinghours',
            options={'ordering': ['day_of_week']},
        ),
        migrations.RemoveField(
            model_name='farmerprofile',
            name='opening_hours_json',
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='day_of_week',
            field=models.CharField(choices=[('Lundi', 'Lundi'), ('Mardi', 'Mardi'), ('Mercredi', 'Mercredi'), ('Jeudi', 'Jeudi'), ('Vendredi', 'Vendredi'), ('Samedi', 'Samedi'), ('Dimanche', 'Dimanche')], max_length=10),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='farmer_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_hours', to='products.farmerprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='openinghours',
            unique_together={('farmer_profile', 'day_of_week')},
        ),
    ]
