# Generated by Django 5.1.3 on 2025-04-02 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_openinghours_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='openinghours',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='openinghours',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='opening_hours_json',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='day_of_week',
            field=models.CharField(choices=[('lundi', 'Lundi'), ('mardi', 'Mardi'), ('mercredi', 'Mercredi'), ('jeudi', 'Jeudi'), ('vendredi', 'Vendredi'), ('samedi', 'Samedi'), ('dimanche', 'Dimanche')], max_length=10),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='farmer_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hours_of_operation', to='products.farmerprofile'),
        ),
    ]
